services:
  postgres:
    image: postgres:15-alpine
    container_name: c2c-platform-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_MULTIPLE_DATABASES: admin_mod_db, auth_db, chat_db, order_db, product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh

volumes:
  postgres_data:
